charity/urls.py
from re import L
from django.urls import path

from .views import LandingPageView, AddDonation, Login, Register

app_name = 'charity'

urlpatterns = [
    path('', LandingPageView.as_view(), name='home'),
    path('add_donation/', AddDonation.as_view(), name='add_donation'),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('charity.urls', namespace='charity'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

charity/models.py
import datetime

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.utils import timezone


class FuntationManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(type_institution='F')

class OrganizationManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(type_institution='OR')

class LocalCollectionManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(type_institution='ZL')

class Category(models.Model):
    """[summary]
    Category model
    """
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Institution(models.Model):
    """[summary]
    Institution model
    """
    TYPE_CHOICES = (
        ('F', 'Fundacja'),
        ('OR', 'Organizacja Pozarządowa'),
        ('ZL', 'Zbiórka Lokalna'),
    )
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(max_length=500)
    type_institution = models.CharField(max_length=100, default='F', choices=TYPE_CHOICES)
    categories = models.ManyToManyField(Category, related_name='categories')

    #   Menager 
    objects = models.Manager()
    fundations = FuntationManager()
    organization = OrganizationManager()
    local = LocalCollectionManager()


    class Meta:
        verbose_name = _('Institution')
        verbose_name_plural = _('Institutions')


    def __str__(self):
        return self.name


class Dotation(models.Model):
    """[summary]
    Dodation model
    """
    quantity = models.PositiveIntegerField(
        verbose_name=_('Ilość'), 
        help_text=_('Wymagany'), 
        default=1, 
        validators=[MinValueValidator(1), MaxValueValidator(100)])
    categories = models.ManyToManyField(Category, related_name='category_selection', verbose_name=_('Category'), help_text=_('Wymagany'))
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    # Dilvery Dotation
    address = models.CharField(verbose_name=_('Adres'), help_text=_('Wymagany'), max_length=255)
    phone_number = models.CharField(verbose_name=_('Numer telefonu'), help_text=_('Wymagany'), max_length=50)
    city = models.CharField(verbose_name=_('Miasto'), help_text=_('Wymagany'), max_length=150)
    postcode = models.CharField(verbose_name=_('Kod Pocztowy'), help_text=_('Wymagany'), max_length=50)
    pick_up_date = models.DateField(verbose_name=_('Data'), help_text=_('Wymagany'), default=timezone.now)
    pick_up_time = models.TimeField(verbose_name=_('Czas'), help_text=_('Wymagany'), default=timezone.now)
    pick_up_comment = models.TextField(verbose_name=_('Komentarz'), help_text=_('Wymagany'), max_length=500, blank=True)
    user = models.ForeignKey(User, help_text=_('Użytkownik'), null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('Dotation')
        verbose_name_plural = _('Dotations')

    

    def __str__(self):
        return self.user
    

   
    

    

    

charity/views.py
from django.db import models
from django.db.models import Sum
from django.db.models.aggregates import Count

from django.views.generic.list import ListView
from django.shortcuts import render
from django.views.generic import TemplateView 


from .models import  Category, Institution, Dotation


class LandingPageView(ListView):
    template_name = 'charity/home.html'
    paginate_by = 10
    model = Institution
    
    


    

   



    
    
    

# class LandingPageView(ListView):
#     template_name = 'charity/home.html'
#     context_object_name = 'institutions'
#     paginate_by = 3

class AddDonation(TemplateView):
    template_name = 'charity/form.html'

class Login(TemplateView):
    template_name = 'registration/login.html'

class Register(TemplateView):
    template_name = 'registration/register.html'

# class InstitutionListView(ListView):
#     model =  Institution
#     queryset = Institution.objects.all().filter(qu)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
  <head>
      
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Pomagaj :)</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>


        <!-- navbar -->
        {% include 'includes/navbar.html' %}

        {% block content %}
        {% endblock %}
    
    
        <!-- footer -->
        {% include 'includes/footer.html' %}

    <script src="{% static 'js/app.js' %}"></script>
  </body>
</html>

templates/charity/form-confirmation.html
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" href="css/style.css" />
  </head>
  <body>
    <header class="header--form-page">
      <nav class="container container--70">
        <ul class="nav--actions">
          <li class="logged-user">
            Witaj Agata
            <ul class="dropdown">
              <li><a href="#">Profil</a></li>
              <li><a href="#">Moje zbiórki</a></li>
              <li><a href="#">Wyloguj</a></li>
            </ul>
          </li>
        </ul>

        <ul>
          <li><a href="index.html" class="btn btn--without-border active">Start</a></li>
          <li><a href="index.html#steps" class="btn btn--without-border">O co chodzi?</a></li>
          <li><a href="index.html#about-us" class="btn btn--without-border">O nas</a></li>
          <li><a href="index.html#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
          <li><a href="index.html#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>
      </nav>

      <div class="slogan container container--90">
          <h2>
            Dziękujemy za przesłanie formularza Na maila prześlemy wszelkie
            informacje o odbiorze.
          </h2>
      </div>
    </header>

    <footer>
      <div class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
          <div class="form-group form-group--50">
            <input type="text" name="name" placeholder="Imię" />
          </div>
          <div class="form-group form-group--50">
            <input type="text" name="surname" placeholder="Nazwisko" />
          </div>

          <div class="form-group">
            <textarea
              name="message"
              placeholder="Wiadomość"
              rows="1"
            ></textarea>
          </div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2018</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"
            ><img src="images/icon-facebook.svg"
          /></a>
          <a href="#" class="btn btn--small"
            ><img src="images/icon-instagram.svg"
          /></a>
        </div>
      </div>
    </footer>

    <script src="js/app.js"></script>
  </body>
</html>

templates/charity/form.html
    <header class="header--form-page">
      <nav class="container container--70">
        <ul class="nav--actions">
          <li class="logged-user">
            Witaj Agata
            <ul class="dropdown">
              <li><a href="#">Profil</a></li>
              <li><a href="#">Ustawienia</a></li>
              <li><a href="#">Wyloguj</a></li>
            </ul>
          </li>
        </ul>

        <ul>
          <li><a href="index.html" class="btn btn--without-border active">Start</a></li>
          <li><a href="index.html#steps" class="btn btn--without-border">O co chodzi?</a></li>
          <li><a href="index.html#about-us" class="btn btn--without-border">O nas</a></li>
          <li><a href="index.html#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
          <li><a href="form.html" class="btn btn--without-border">Przekaż dary</a></li>
          <li><a href="index.html#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>
      </nav>

      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Oddaj rzeczy, których już nie chcesz<br />
            <span class="uppercase">potrzebującym</span>
          </h1>

          <div class="slogan--steps">
            <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
            <ul class="slogan--steps-boxes">
              <li>
                <div><em>1</em><span>Wybierz rzeczy</span></div>
              </li>
              <li>
                <div><em>2</em><span>Spakuj je w worki</span></div>
              </li>
              <li>
                <div><em>3</em><span>Wybierz fundację</span></div>
              </li>
              <li>
                <div><em>4</em><span>Zamów kuriera</span></div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </header>

    <section class="form--steps">
      <div class="form--steps-instructions">
        <div class="form--steps-container">
          <h3>Ważne!</h3>
          <p data-step="1" class="active">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="2">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="3">
           Wybierz jedną, do
            której trafi Twoja przesyłka.
          </p>
          <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
        </div>
      </div>

      <div class="form--steps-container">
        <div class="form--steps-counter">Krok <span>1</span>/5</div>

        <form action="form-confirmation.html" method="post">
          <!-- STEP 1: class .active is switching steps -->
          <div data-step="1" class="active">
            <h3>Zaznacz co chcesz oddać:</h3>

            <div class="form-group form-group--checkbox">
              <label>
                <input
                  type="checkbox"
                  name="categories"
                  value="clothes-to-use"
                />
                <span class="checkbox"></span>
                <span class="description"
                  >ubrania, które nadają się do ponownego użycia</span
                >
              </label>
            </div>

            <div class="form-group form-group--checkbox">
              <label>
                <input
                  type="checkbox"
                  name="categories"
                  value="clothes-useless"
                />
                <span class="checkbox"></span>
                <span class="description">ubrania, do wyrzucenia</span>
              </label>
            </div>

            <div class="form-group form-group--checkbox">
              <label>
                <input type="checkbox" name="categories" value="toys" />
                <span class="checkbox"></span>
                <span class="description">zabawki</span>
              </label>
            </div>

            <div class="form-group form-group--checkbox">
              <label>
                <input type="checkbox" name="categories" value="books" />
                <span class="checkbox"></span>
                <span class="description">książki</span>
              </label>
            </div>

            <div class="form-group form-group--checkbox">
              <label>
                <input type="checkbox" name="categories" value="other" />
                <span class="checkbox"></span>
                <span class="description">inne</span>
              </label>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 2 -->
          <div data-step="2">
            <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

            <div class="form-group form-group--inline">
              <label>
                Liczba 60l worków:
                <input type="number" name="bags" step="1" min="1" />
              </label>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>



          <!-- STEP 4 -->
          <div data-step="3">
            <h3>Wybierz organizacje, której chcesz pomóc:</h3>

            <div class="form-group form-group--checkbox">
              <label>
                <input type="radio" name="organization" value="old" />
                <span class="checkbox radio"></span>
                <span class="description">
                  <div class="title">Fundacja “Bez domu”</div>
                  <div class="subtitle">
                    Cel i misja: Pomoc dla osób nie posiadających miejsca
                    zamieszkania
                  </div>
                </span>
              </label>
            </div>

            <div class="form-group form-group--checkbox">
              <label>
                <input type="radio" name="organization" value="old" />
                <span class="checkbox radio"></span>
                <span class="description">
                  <div class="title">Fundacja “Dla dzieci"</div>
                  <div class="subtitle">
                    Cel i misja: Pomoc osobom znajdującym się w trudnej sytuacji
                    życiowej.
                  </div>
                </span>
              </label>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 5 -->
          <div data-step="4">
            <h3>Podaj adres oraz termin odbioru rzecz przez kuriera:</h3>

            <div class="form-section form-section--columns">
              <div class="form-section--column">
                <h4>Adres odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Ulica <input type="text" name="address" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Miasto <input type="text" name="city" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Kod pocztowy <input type="text" name="postcode" />
                  </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Numer telefonu <input type="phone" name="phone" />
                  </label>
                </div>
              </div>

              <div class="form-section--column">
                <h4>Termin odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Data <input type="date" name="data" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Godzina <input type="time" name="time" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Uwagi dla kuriera
                    <textarea name="more_info" rows="5"></textarea>
                  </label>
                </div>
              </div>
            </div>
            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 6 -->
          <div data-step="5">
            <h3>Podsumowanie Twojej darowizny</h3>

            <div class="summary">
              <div class="form-section">
                <h4>Oddajesz:</h4>
                <ul>
                  <li>
                    <span class="icon icon-bag"></span>
                    <span class="summary--text"
                      >4 worki ubrań w dobrym stanie dla dzieci</span
                    >
                  </li>

                  <li>
                    <span class="icon icon-hand"></span>
                    <span class="summary--text"
                      >Dla fundacji "Mam marzenie" w Warszawie</span
                    >
                  </li>
                </ul>
              </div>

              <div class="form-section form-section--columns">
                <div class="form-section--column">
                  <h4>Adres odbioru:</h4>
                  <ul>
                    <li>Prosta 51</li>
                    <li>Warszawa</li>
                    <li>99-098</li>
                    <li>123 456 789</li>
                  </ul>
                </div>

                <div class="form-section--column">
                  <h4>Termin odbioru:</h4>
                  <ul>
                    <li>13/12/2018</li>
                    <li>15:40</li>
                    <li>Brak uwag</li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="submit" class="btn">Potwierdzam</button>
            </div>
          </div>
        </form>
      </div>
    </section>

    <footer>
      <div class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
          <div class="form-group form-group--50">
            <input type="text" name="name" placeholder="Imię" />
          </div>
          <div class="form-group form-group--50">
            <input type="text" name="surname" placeholder="Nazwisko" />
          </div>

          <div class="form-group">
            <textarea
              name="message"
              placeholder="Wiadomość"
              rows="1"
            ></textarea>
          </div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2018</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"
            ><img src="images/icon-facebook.svg"
          /></a>
          <a href="#" class="btn btn--small"
            ><img src="images/icon-instagram.svg"
          /></a>
        </div>
      </div>
    </footer>

    <script src="js/app.js"></script>
  </body>
</html>

templates/charity/home.html
{% extends '../base.html'%}
{% load static %}

{% block content %}


  <section id="stats" class="stats">
    <div class="container container--85">
      
      <div class="stats--item">
        <em>{{ quantity_bags }}</em>
        <!-- <em>{{ quantity_bags }}</em> -->
        <h3>Oddanych worków</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius est beatae, quod accusamus illum tempora!</p>
      </div>

      <div class="stats--item">
        <em>{{ institution_qty }}</em>
        <h3>Wspartych organizacji</h3>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam magnam, sint nihil cupiditate quas quam.</p>
      </div>
    </div>
  </section>

  <section id="steps" class="steps">
    <h2>Wystarczą 4 proste kroki</h2>

    <div class="steps--container">
      <div class="steps--item">
        <span class="icon icon--hands"></span>
        <h3>Wybierz rzeczy</h3>
        <p>ubrania, zabawki, sprzęt i inne</p>
      </div>
      <div class="steps--item">
        <span class="icon icon--arrow"></span>
        <h3>Spakuj je</h3>
        <p>skorzystaj z worków na śmieci</p>
      </div>
      <div class="steps--item">
        <span class="icon icon--glasses"></span>
        <h3>Zdecyduj komu chcesz pomóc</h3>
        <p>wybierz zaufane miejsce</p>
      </div>
      <div class="steps--item">
        <span class="icon icon--courier"></span>
        <h3>Zamów kuriera</h3>
        <p>kurier przyjedzie w dogodnym terminie</p>
      </div>
    </div>

    <a id='id-sekcji' href="{% url 'charity:register' %}" class="btn btn--large">Załóż konto</a>
  </section>

  <section id="about-us" class="about-us">
    <div class="about-us--text">
      <h2>O nas</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas vitae animi rem pariatur incidunt libero optio esse quisquam illo omnis.</p>
      <img src="{% static 'images/signature.svg' %}" class="about-us--text-signature" alt="Signature" />
    </div>
    <div class="about-us--image"><img src="{% static 'images/about-us.jpg' %}" alt="People in circle" /></div>
  </section>

   <section id="help" class="help">
    <h2>Komu pomagamy?</h2>

    <ul class="help--buttons">
      <li data-id="1"><a href="#" class="btn btn--without-border active">Fundacjom</a></li>
      <li data-id="2"><a href="#" class="btn btn--without-border">Organizacjom pozarządowym</a></li>
      <li data-id="3"><a href="#" class="btn btn--without-border">Lokalnym zbiórkom</a></li>
    </ul>

   <!-- SLIDE 1 -->
   <div class="help--slides active" data-id="1">
    <p>W naszej bazie znajdziesz listę zweryfikowanych Fundacji, z którymi współpracujemy. Możesz sprawdzić czym się zajmują, komu pomagają i czego potrzebują.</p>

    <ul class="help--slides-items">
      {% for fundation in fundations %}
        {% for category in fundation.categories.all %}
            <li>
              <div class="col">
                <div class="title">Fundacja "{{ fundation.name }}"</div>
                <div class="subtitle">Cel i misja: {{ fundation.description|truncatechars:100  }}</div>
              </div>
              
              <div class="col"><div class="text">{{ category.name }}</div></div>
            </li>
        {% endfor %}
      {% endfor %}
    </ul>

    <div class="pagination">
      <span class="step-links">
          {% if page_obj.has_previous %}
              <a href="?page=1">&laquo; 1</a>
              <a href="?page={{ page_obj.previous_page_number }}">2</a>
          {% endif %}
  
          <span class="current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>
  
          {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}">3</a>
              <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
          {% endif %}
      </span>
  </div>
  
   
  </div>


    <!-- SLIDE 2 -->
    <div class="help--slides" data-id="2">
      <p>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic officiis mollitia dolor, neque aspernatur accusamus debitis. Ducimus, officia. Quia, sunt illum! Non iste placeat ab ipsum alias
        quos suscipit corporis!
      </p>
      <ul class="help--slides-items">
        {% for organization in organizations %}
          {% for category in organization.categories.all %}
              <li>
                <div class="col">
                  <div class="title">Fundacja "{{ organization.name }}"</div>
                  <div class="subtitle">Cel i misja: {{ organization.description|truncatechars:100  }}</div>
                </div>
                
                <div class="col"><div class="text">{{ category.name }}</div></div>
              </li>
          {% endfor %}
        {% endfor %}
      </ul>

      <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
     
    </div>

    <!-- SLIDE 3 -->
    <div class="help--slides" data-id="3">
      <p>Lorem ipsum dolor sit amet, his ocurreret persequeris ea, ad utinam laudem duo. Verterem adipisci partiendo eos ne, ea his reque quaeque recteque, ne quo lobortis intellegam.</p>
      <ul class="help--slides-items">
        {% for local in locals %}
          {% for category in local.categories.all %}
              <li>
                <div class="col">
                  <div class="title">Fundacja "{{ local.name }}"</div>
                  <div class="subtitle">Cel i misja: {{ local.description|truncatechars:100  }}</div>
                </div>
                
                <div class="col"><div class="text">{{ category.name }}</div></div>
              </li>
          {% endfor %}
        {% endfor %}
      </ul>
      <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    </div>
  </section>

  <script>
    $()
  </script>

  {% endblock %}

templates/charity/pagination.html
<div class="pagination">
    <span class="step-links">
      {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Poprzednia</a>
      {% endif %}
    <span class="current">
      Strona {{ page.number }} z {{ page.paginator.num_pages }}.
    </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Następna</a>
      {% endif %}
  </span>

templates/charity/sub_base.html
{% extends "../base.html" %}
{% load static %}


{% block content %}



{% endblock %}

templates/includes/footer.html
{% load static%}
<footer>
    <div id="contact" class="contact">
      <h2>Skontaktuj się z nami</h2>
      <h3>Formularz kontaktowy</h3>
      <form class="form--contact">
        <div class="form-group form-group--50"><input type="text" name="name" placeholder="Imię" /></div>
        <div class="form-group form-group--50"><input type="text" name="surname" placeholder="Nazwisko" /></div>

        <div class="form-group"><textarea name="message" placeholder="Wiadomość" rows="1"></textarea></div>

        <button class="btn" type="submit">Wyślij</button>
      </form>
    </div>
    <div class="bottom-line">
      <span class="bottom-line--copy">Copyright &copy; 2019</span>
      <div class="bottom-line--icons">
        <a href="#" class="btn btn--small"><img src="{% static 'images/icon-facebook.svg' %}"/></a>
        <a href="#" class="btn btn--small"><img src="{% static 'images/icon-instagram.svg' %}"/></a>
      </div>
    </div>
  </footer>

templates/includes/navbar.html
{% load static %}
<header class="header--main-page">

    <nav class="container container--70">
        <ul class="nav--actions">
          <li><a id='id-sekcji' href="{% url 'charity:login' %}" class="btn btn--small btn--without-border">Zaloguj</a></li>
          <li><a id='id-sekcji' href="{% url 'charity:register' %}#" class="btn btn--small btn--highlighted">Załóż konto</a></li>
        </ul>
  
        <ul>
          <li><a id='id-sekcji' href="{% url 'charity:home' %}" class="btn btn--without-border active">Start</a></li>
          <li><a id='id-sekcji' href="{% url 'charity:home' %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
          <li><a id='id-sekcji' href="{% url 'charity:home' %}#about-us" class="btn btn--without-border">O nas</a></li>
          <li><a id='id-sekcji' href="{% url 'charity:home' %}#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
          <li><a id='id-sekcji' href="{% url 'charity:add_donation' %}" class="btn btn--without-border">Przekaż dary</a></li>
          <li><a id='id-sekcji' href="{% url 'charity:home' %}#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>
      </nav>

    <div class="slogan container container--90">
      <div class="slogan--item">
        <h1>
          Zacznij pomagać!<br />
          Oddaj niechciane rzeczy w zaufane ręce
        </h1>
      </div>
    </div>
  </header>